version: '3.8'

services:
  app:
    build:
      args:
        user: jmontes
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html/app
    volumes:
      - ./:/var/www/html/app
    networks:
      - network-laravel-app

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/app
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - network-laravel-app

networks:
  network-laravel-app:
    driver: bridge
